// Exercise the real native client handler using only synthetic trust/flow files.
// This never runs the installed service, types input, or reads its credentials.
#define wmain UnusedHelperEntrypoint
#include "main.cpp"
#undef wmain
#include <iostream>
#include <stdexcept>
#include <thread>

namespace {
void Check(bool condition, const char* message) {
  if (!condition) throw std::runtime_error(message);
}

bool NeverUnlocked() { return false; }

void SaveSyntheticTrust(bool trusted = true) {
  const std::string token = std::string(43, 'A') + "=";
  std::string protected_snapshot;
  const std::string snapshot = trusted ?
      "v1\nsynthetic-phone\t" + Base64Encode(BytesFromString(token)) + "\n" : "v1\n";
  Check(ProtectSecret(snapshot, &protected_snapshot), "Encrypt synthetic trust");
  Check(WriteTextFile(CompanionTrustPath(),
      "{\"trustedDevicesDpapiB64\":\"" + JsonEscape(protected_snapshot) + "\"}"), "Write synthetic trust");
}

class Connection {
 public:
  SOCKET client = INVALID_SOCKET;
  HANDLE stop_event = CreateEventW(nullptr, TRUE, FALSE, nullptr);
  std::thread worker;
  Connection() {
    SOCKET listener = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    Check(listener != INVALID_SOCKET, "Create loopback listener");
    sockaddr_in address{};
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    Check(bind(listener, reinterpret_cast<sockaddr*>(&address), sizeof(address)) == 0, "Bind loopback");
    int size = sizeof(address);
    Check(getsockname(listener, reinterpret_cast<sockaddr*>(&address), &size) == 0, "Query loopback port");
    Check(listen(listener, 1) == 0, "Listen loopback");
    client = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    Check(connect(client, reinterpret_cast<sockaddr*>(&address), sizeof(address)) == 0, "Connect loopback");
    SOCKET server = accept(listener, nullptr, nullptr);
    closesocket(listener);
    Check(server != INVALID_SOCKET, "Accept loopback");
    DWORD timeout = 3000;
    setsockopt(client, SOL_SOCKET, SO_RCVTIMEO, reinterpret_cast<const char*>(&timeout), sizeof(timeout));
    worker = std::thread([this, server] {
      HandlePreloginClient(server, stop_event, NeverUnlocked);
      shutdown(server, SD_BOTH);
      closesocket(server);
    });
  }
  ~Connection() {
    SetEvent(stop_event);
    shutdown(client, SD_BOTH);
    closesocket(client);
    worker.join();
    CloseHandle(stop_event);
  }
  void Upgrade() {
    Check(SocketSendText(client, "GET /automation HTTP/1.1\r\nHost: localhost\r\n"
        "Upgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\n"
        "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n\r\n"), "Send upgrade");
    std::string response;
    Check(ReadHttpUpgradeRequest(client, &response) && response.find("101 Switching Protocols") != std::string::npos,
        "Upgrade accepted");
  }
  void Send(const std::string& payload) {
    std::vector<uint8_t> frame{0x81};
    if (payload.size() < 126) frame.push_back(static_cast<uint8_t>(0x80 | payload.size()));
    else {
      Check(payload.size() <= 65535, "Bound fixture size");
      frame.push_back(0xfe);
      frame.push_back(static_cast<uint8_t>(payload.size() >> 8));
      frame.push_back(static_cast<uint8_t>(payload.size()));
    }
    const uint8_t mask[] = {0x21, 0x32, 0x43, 0x54};
    frame.insert(frame.end(), mask, mask + 4);
    for (size_t index = 0; index < payload.size(); ++index)
      frame.push_back(static_cast<uint8_t>(payload[index]) ^ mask[index % 4]);
    Check(SocketSendAll(client, frame.data(), frame.size()), "Send masked frame");
  }
  std::string Receive() {
    std::string message;
    Check(ReceiveWebSocketText(client, &message), "Receive native response");
    return message;
  }
};
}  // namespace

int wmain(int argc, wchar_t* argv[]) {
  try {
    Check(argc == 2, "Pass the Gson client_info fixture generated by Android regression tests");
    const std::string android_wire = ReadTextFile(fs::path(argv[1]));
    Check(android_wire.find("\\u003d") != std::string::npos, "Fixture must use real Gson escaping");
    Check(ExtractJsonString(android_wire, "deviceSecret") == std::string(43, 'A') + "=", "Gson token must decode exactly");
    Check(ExtractJsonString(R"({"name":"\u0b95\uD83D\uDD13"})", "name") == "\xe0\xae\x95\xf0\x9f\x94\x93", "Unicode and surrogate pair decoding");
    Check(ExtractJsonString(R"({"note":"deviceSecret","other":"wrong","deviceSecret":"right"})", "deviceSecret") == "right", "Key-like values must be skipped");
    for (const std::string invalid : {R"({"key":"\u00x1"})", R"({"key":"\uD800"})", R"({"key":"\uDC00"})", R"({"key":"unterminated})"})
      Check(ExtractJsonString(invalid, "key").empty(), "Malformed strings must be rejected");

    // Only this process sees the test ProgramData root. The production service is untouched.
    const fs::path fixture = fs::current_path() / (L"synthetic-prelogin-" + std::to_wstring(GetCurrentProcessId()));
    fs::create_directories(fixture);
    Check(SetEnvironmentVariableW(L"ProgramData", fixture.c_str()) != FALSE, "Set isolated fixture root");
    Check(WriteTextFile(CredentialIdentityPath(), R"({"deviceId":"agent-a","deviceName":"Synthetic desktop"})"), "Write synthetic identity");
    Check(WriteTextFile(CredentialPathForFlow("unlock-one"), R"({"flowId":"unlock-one","flowName":"Unlock one"})"), "Write first flow metadata");
    Check(WriteTextFile(CredentialPathForFlow("unlock-two"), R"({"flowId":"unlock-two","flowName":"Unlock two"})"), "Write second flow metadata");
    SaveSyntheticTrust();
    WSADATA winsock{};
    Check(WSAStartup(MAKEWORD(2, 2), &winsock) == 0, "Start test Winsock");
    g_service_stop_event = CreateEventW(nullptr, TRUE, FALSE, nullptr);
    {
      Connection connection;
      connection.Upgrade();
      connection.Send(android_wire);
      const auto auth = connection.Receive();
      Check(ExtractJsonString(auth, "status") == "authenticated" && ExtractJsonBool(auth, "prelogin"), "Native helper must authenticate the Android wire token");
      connection.Send(R"({"type":"list_flows","transactionId":"fresh-boot"})");
      const auto flows = connection.Receive();
      Check(ExtractJsonString(flows, "type") == "flow_list_response" &&
          ExtractJsonString(flows, "transactionId") == "fresh-boot" &&
          flows.find("unlock-one") != std::string::npos && flows.find("unlock-two") != std::string::npos,
          "Native helper must serve persisted flow metadata without a desktop app");
      SaveSyntheticTrust(false);
      connection.Send(R"({"type":"list_flows","transactionId":"after-revocation"})");
      Check(ExtractJsonString(connection.Receive(), "status") == "pairing_revoked", "Revocation must still reject commands");
    }
    SaveSyntheticTrust();
    {
      Connection connection;
      connection.Upgrade();
      connection.Send(R"({"type":"client_info","deviceId":"synthetic-phone","deviceSecret":"wrong"})");
      Check(ExtractJsonString(connection.Receive(), "status") == "authentication_failed", "Incorrect token must remain rejected");
    }
    CloseHandle(g_service_stop_event);
    g_service_stop_event = nullptr;
    WSACleanup();
    std::cout << "Native pre-login wire authentication, persisted flow listing, and revocation passed\n";
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "FAIL: " << error.what() << '\n';
    return 1;
  }
}
